[package]
name = "solxplain"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
borsh = "1.6.0"
clap = "4.5.53"
hex = "0.4.3"
serde = "1.0.228"
solana-client = "3.1.5"
solana-sdk = "3.0.0"
solana-transaction-status = "3.1.5"
tokio = { version = "1.48.0", features = ["full"] }
